#!/bin/sh

# Aborting commit due to empty commit message.
grep -v '#' $1 | grep -v '^$' > /dev/null 
if [ $? -eq 1 ]; then
  exit
fi

grep -v '^#' $1 | grep 'refs #[0-9]\+$' > /dev/null
if [ $? -eq 0 ]; then
  exit
fi

echo "\033[31m[ERROR] can't commit without issue id!!\033[0m"
exit 1
